package Enums;

public enum tokenType {
    IDENFR, INTCON, STRCON, MAINTK, CONSTTK, INTTK, BREAKTK, CONTINUETK, IFTK, ELSETK, NOT, AND, OR, FORTK,
    GETINTTK, PRINTFTK, RETURNTK, PLUS, MINU, VOIDTK, ASSIGN, SEMICN, COMMA, LPARENT, RPARENT, LBRACK, RBRACK,
    LBRACE, RBRACE, NEQ, EQL, GEQ, GRE, LEQ, LSS, MOD, DIV, MULT
}
